### ISSUE TITLE
debug in index.js is not passing through errors

### ISSUE THREAD

**Issue by jkatsnelson** [contentful-labs/contentful-metalsmith#11]
Hey, I had to dive into the code and add a console.log to see an error show up. I think something is wrong with the debug code.

**Comment by grncdr** [comment]
Hi @jkatsnelson, we're using [debug](https://www.npmjs.com/package/debug) which means you need to set the `DEBUG` env var to include `contentful-metalsmith` to see debug output.

OTOH it seems like we might want to allow errors there to bubble up. I'm going to open a PR for that.

**Comment by grncdr** [comment]
could you give the branch above a try and see if it behaves how you'd expect?

**Comment by grncdr** [comment]
Closed by #13, please re-open the issue if we've misunderstood the issue.
