### ISSUE TITLE
Usage with metalsmith-layouts

### ISSUE THREAD

**Issue by cameronjroe** [contentful-labs/contentful-metalsmith#19]
I'm trying to set up contentful with metalsmith-layouts and wondering how I would do so. I currently have markdown file with:

```
---
layout: about.liquid
title: About
contentful:
  space_id: 4ek2vxiathe3
permalink: about
---

some content here..
```

I'm using liquid and in the template I have:

```
{% for entry in contentful.entries %}
    {{entry}}
{% endfor %}
```

I'm not able to get anything from `entry`. Is there a way to use contentful with layouts and have the entries available?

**Comment by cameronjroe** [comment]
Any thoughts on this?

**Comment by cameronjroe** [comment]
?

**Comment by trodrigues** [comment]
Hi there,

first of all, apologies for the delay in this reply.

It seems like this integration isn't working properly with newer versions of metalsmith at all.

However, we have decided that we won't be officially supporting this package for now, so it might be a good idea to look at some of the forks and see if they work properly with newer versions of metalsmith.

**Comment by cameronjroe** [comment]
Sure. Thanks for the update.
