### ISSUE TITLE
add version to package.json

### ISSUE THREAD

**Issue by bnchdrff** [contentful-labs/contentful-metalsmith#21]
Thanks for the refactor work; i've been following it for a new project 😀

Can you add a version to package.json so I install the new release?

**Comment by stefanjudis** [comment]
The project is already released and you can use it. :)

https://www.npmjs.com/package/contentful-metalsmith

The version field was dropped by the semantic-release setup. It takes care of all the publishes automatically. In case you run into any problems let me know. :)

https://github.com/semantic-release/semantic-release#why-is-the-packagejsons-version-not-updated-in-my-repository

**Comment by bnchdrff** [comment]
Neat. thank u!
