### ISSUE TITLE
Ability to load content once and being available in every source file

### ISSUE THREAD

**Issue by stefanjudis** [contentful-labs/contentful-metalsmith#22]
As a user I'd like to specify some general information in the `metalsmith.json` and then have it available everywhere.

E.g. 

```
  "source": "src",
  "destination": "build",
  "plugins": {
    "contentful-metalsmith": {
      "access_token": "YOUR_CONTENTFUL_ACCESS_TOKEN",
      "space_id": "YOUR_CONTENTFUL_SPACE_ID"
      "common": {
        "singleEntry" : {
          "entry_id": "..."
        },
        "collection": {
          "content_type": "books"
        }
      }
    }
  }
}
```

And then inside of the templates

```
<div>{{ data.common.foo.fields.title }}</div>

{{#each data.common.books}}
  {{ fields.title }}
{{/each}}
```

**Comment by bnchdrff** [comment]
This would also be useful in the case of adding dynamic query arguments -- for example "load a collection content_type name `books` and `fields.expire_time[lt]` is `date.toISOString()`"

**Comment by Khaledgarbaya** [comment]
I think you do that using a combination of content_type and query param

**Comment by Khaledgarbaya** [comment]
Hi @bnchdrff I think you do that using a combination of content_type and query param

**Comment by bnchdrff** [comment]
yes, but as far as i can tell that's only available as a source option -- if content queries were available through the global configuration, then i could supply a javascript expression as the argument for filter.query.

**Comment by bnchdrff** [comment]
yes, but as far as i can tell that's only available as a source option -- if content queries were available through the global configuration, then i could supply a javascript expression as the argument for filter.query.

**Comment by bnchdrff** [comment]
yes, but as far as i can tell that's only available as a source option -- if content queries were available through the global configuration, then i could supply a javascript expression as the argument for filter.query.

**Comment by bnchdrff** [comment]
so, how would the interface for something like this look?

what if we had a configuration property `common` that is an array of queries in the same style as what is used in the source files, like this:

```js
  // ...
  "common": [
    {
      "identifier": "megathreads", // this query's result would be available as data.common.megathreads
      "query": {
        "content_type": "thread",
        "filter": {
          "fields.isMegathread": 1,
        },
      },
    },
  ],
  // ...
```

If the processor is expecting a format similar to the existing one, we could share some code between the two.

**Comment by stefanjudis** [comment]
@bnchdrff Yep, that's the idea. 👍 

I wouldn't go with an array as with an object we wouldn't need the `identifier`.

```
 // ...
  "common": {
   megathreads: {
      "query": {
        "content_type": "thread",
        "filter": {
          "fields.isMegathread": 1,
        },
      },
    },
  },
  // ...

Not sure about the snake_case in json files, though. But yeah, that's not a huge issue. But for better usage I'd go with camel case here. I'd be a little bit "what? snake case in json?" - is it's a bit uncommon I think.

**Comment by bnchdrff** [comment]
yeah camelCase sounds good -- i initially was thinking snake_case matched the contentful api but it actually would be coolest to have our property names correlate with what the API uses!

**Comment by bnchdrff** [comment]
i'm thiking that the common content should be tied to the contentful client -- when `getContentfulClient` establishes the shared client, we should also read config options, find any common queries, and load that data.

to do this, it might be helpful to treat the client as an instantiated class -- seem reasonable?

**Comment by stefanjudis** [comment]
hey hey,

not a big fan of that. :)

https://github.com/contentful-labs/contentful-metalsmith/blob/master/lib/processor.js#L119-L121

I'd go with just resolving the common requests there -☝️  and pass it down the chain.
Wouldn't need a big refactoring and does the job. 

What do you think? :)

**Comment by bnchdrff** [comment]
cool sounds good. workin on it. 🔨 🎎 🏠

**Comment by stefanjudis** [comment]
Sweet!

**Comment by bnchdrff** [comment]
cool, thanks so much

**Comment by stefanjudis** [comment]
@bnchdrff 

👉  https://github.com/contentful-labs/contentful-metalsmith/pull/27#issuecomment-248852896
