### ISSUE TITLE
Is there any way to handle subfolders

### ISSUE THREAD

**Issue by dohomi** [contentful-labs/contentful-metalsmith#38]
Hello,

I'm very new to contentful and metalsmith. I'm validating at the moment if I'm going to use it in an upcoming project. What I currently don't understand is, how to handle a page tree structure of pages and subpages. In one of my projects I want to convert a website which has around 3 - 4 levels deep nested pages into a contentful project. 

Is there any way how to realize this? I'd love to see some examples and to how to implement this.
Thanks

**Comment by stefanjudis** [comment]
@dohomi 

I'm not in the office today. I can try to provide an example tomorrow.

**Comment by dohomi** [comment]
great thanks!

**Comment by stefanjudis** [comment]
@dohomi 

Okay. So. :)

I just played around with it. I set up several pages including a `parent` fields.
And I rendered the following structure:

![bildschirmfoto 2016-11-15 um 15 06 26](https://cloud.githubusercontent.com/assets/962099/20308631/1ffd26ca-ab45-11e6-926b-b02267f3609c.png)

So I had a root element and children, which also had children.

To achieve this rendered result I used https://github.com/contentful-labs/contentful-metalsmith/blob/master/docs/source-file-settings.md#entry_filename_builder-optional.

## 1. Set up a base file for your pages

`page.html`
```
---
title: Contentful Pages
contentful:
  content_type: page
  entry_filename_builder: tree_builder
  entry_template: page.html
layout: index.html
---
```

I set the property `entry_filename_builder`. So what this does it renders all entries with the content type `page` using the template `page.html`. To figure out the filename ( and folder structure ) a tree_builder function is used.

## 2. Define tree_builder

In my `build.js` file i defined then the `tree_builder` function.

```
.use(contentful({
    space_id: 'lat5prfuqt5q',
    access_token: '2cfba1688e51e5c3ffd144a66a50073af37be3d62d9b16fda427dc5db6aa1264',
    filenameBuilders: {
      tree_builder: (entry) => {
        function getTreePath(path, entry) {
          path = path || '';

          path = path ?
                entry.fields.slug + '/' + path :
                entry.fields.slug;

          if (entry.fields.parent) {
            return getTreePath(path, entry.fields.parent);
          }

          return path + '.html';
        }

        return getTreePath(null, entry);
      }
    }
  }))
```

This walks recursive the way up until there is not parent anymore. This way the folder structure can be achieved.

Does this answer your question?

**Comment by dohomi** [comment]
Hi @stefanjudis great stuff! Basically you would add a `parent` property with type `page` for each child? Thanks for this, saved me tons of time!

**Comment by stefanjudis** [comment]
Anytime. Glad I could help. :)

> Basically you would add a parent property with type page for each child?

Yeah kind of... I'm not quite sure what your goals and your exact structure are. Pretty much depends on what you want to do. :)

If you have any further questions let me know. :)
