### ISSUE TITLE
data:true and no fields available

### ISSUE THREAD

**Issue by dohomi** [contentful-labs/contentful-metalsmith#39]
I am trying to get started and try to render the index.html als main page with following setup:

```
---
title: Contentful Blog Example space
contentful:
entry_id: rVbXPWnNoyOAoweQay0ac
layout: page.html
---
```

but the only result for data is `data: true`. Any idea what I could do wrong possibly?

Thanks

**Comment by dohomi** [comment]
I went one step back: cloned the `contentful-metalsmith-example` and simply changed `space_id` and `access_token` and only try to render `index.html` but still there isn't any data available. 
```
---
title: Mainpage of planet
contentful:
  content_type: page
layout: page.html
---
```
```
 {{#each this}}
        {{@key}}: {{this}}
 {{/each}}
```
The printout only shows still `data:true`. Is there any other settings to change besides the `space_id` and `access_token`? `npm run` and `npm run dev` seems to work, only the data context of the content is missing.

**Comment by stefanjudis** [comment]
@dohomi 

> content_type: page

This is supposed to be the content type id. It might be that the content type ID is not `page`?

**Comment by dohomi** [comment]
@stefanjudis it was my fault.. some handlebar mistake.
