### ISSUE TITLE
Please Give simple example of contentful-metalsmith ?

### ISSUE THREAD

**Issue by surajdalvi** [contentful-labs/contentful-metalsmith#4]
I am not getting https://github.com/contentful-labs/contentful-metalsmith-example these example. please give me simple example?

**Comment by madtrick** [comment]
[contentful-metalsmith-example](https://github.com/contentful-labs/contentful-metalsmith-example) is a example project that shows how can you use the [contentful-metalsmith](https://github.com/contentful-labs/contentful-metalsmith) to create static websites using content stored at [www.contentful.com](www.contentful.com).

In this project we configure the plugin to fetch data and generate three different types of pages:

* albums, [configured](https://github.com/contentful-labs/contentful-metalsmith-example/blob/master/src/albums.html#L3-L6) to fetch all the entries with content type `album`
* venues, [configured](https://github.com/contentful-labs/contentful-metalsmith-example/blob/master/src/venues.html#L3-L8) to fetch all the entries with content type `venue` and located in the United Kingdom or USA
*  entries, [configured](https://github.com/contentful-labs/contentful-metalsmith-example/blob/master/src/entries.html#L3-L4) to fetch all the entries in the space no matter their content type

The README file in this project [explain](https://github.com/contentful-labs/contentful-metalsmith#setup-a-source-file) all the configuration parameters mentioned in the files linked above.

Hope this helps

**Comment by surajdalvi** [comment]
Hi,

  I  created one space in contentful ,name of space is **Test**  then i create Content Type into these Space whose name is **Blogs**  i add two fields for these Content Type , whose name is Name and Description. Then i add one entry for the  Content Type. Now i want to generate static site for this space entries ,using  **contentful-metalsmith**  plugin. To Get these i create **metalsmith.json**  file and write following content into it:

{
  "source": "src",
  "destination": "build",
  "plugins": {
    "contentful-metalsmith": {
      "accessToken" : "951881574b46c1b92a2a205dc789f1c029c306c41a4640e5b1cb76cd5162aa57"
    },
    "metalsmith-templates" : {
      "engine" : "handlebars",
      "directory" : "templates"
    }
    
  }
}

then i create **source** directory and create **home.html** file into it , and write following content into it:
  ---
  title: Test
  contentful:
      space_id: zvodetponx9t
  template: home.html
  ---

then i create **templates** directory and create **home.html** file into it , and  write following content into it:

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <title>{{ title }}</title>
</head>
<body>
    <div class="main-wrapper">
        {{ contents }}
    </div>

</body>
</html>



Now i run these project but i am not get desired output? please help me into it wheather i am doing anything wrong ? What i do to get desire output?

**Comment by madtrick** [comment]
@surajdalvi you said that you created the `source` directory but in your configuration file the source directory name is `src`. Can you confirm that you created the correct folder?

Also, could you run with the debug flag on and paste here the output? To enable the debug flag, prefix the `metalsmith` command with `DEBUG=contentful-metalsmith` like this:

```shell
DEBUG=contentful-metalsmith ./node_modules/metalsmith/bin/metalsmith
```

**Comment by grncdr** [comment]
Please re-open this issue if the problem is still occurring.
