### ISSUE TITLE
rendering multiple content types inside of a reference array

### ISSUE THREAD

**Issue by dohomi** [contentful-labs/contentful-metalsmith#40]
Hello,
I'm coming from TYPO3 CMS and still trying to figure out if contentful is the right choice for me. I created a default page type with all required fields for each page:
```
  "name": "Page",
  "description": "typical page type",
  "displayField": "title",
  "fields": [
    {
      "name": "title",
      "id": "title",
      "type": "Symbol",
      "required": true,
      "validations": [],
      "localized": true,
      "disabled": false,
      "omitted": false
    },
    {
      "name": "slug",
      "id": "slug",
      "type": "Symbol",
      "required": true,
      "validations": []
    },
    {
      "name": "Meta",
      "id": "meta",
      "type": "Link",
      "linkType": "Entry",
      "validations": [
        {
          "linkContentType": [
            "meta"
          ]
        }
      ]
    },
    {
      "name": "Parent Page",
      "id": "parentPage",
      "type": "Link",
      "linkType": "Entry",
      "validations": [
        {
          "linkContentType": [
            "page"
          ]
        }
      ]
    },
    {
      "name": "Content",
      "id": "content",
      "type": "Array",
      "items": {
        "type": "Link",
        "linkType": "Entry",
        "validations": []
      },
      "validations": []
    }
  ]
```
Inside of `Content` I store all different content types for each page element inside an array. What I didn't understand for now, how can I assign a template for each content type? I think in total there will be around 15-20 different `content types` created through the `content model`. Is there any recommended way how to render this?

**Comment by dohomi** [comment]
Here is my example output.. but I don't see how to get the content type:
```
{{#each data.entries}}

    {{#each fields.content}}

    {{#each fields}}
    {{this}}<br>
    {{/each}}
    {{/each}}
    {{/each}}```

**Comment by floelhoeffel** [comment]
@dohomi - in an ideal world content is modeled without relationship to presentation. So content and presentation are strictly decoupled. What you could do is map a template in metalsmith to a contentType by its id or even create a custom mapping. It is also possible to store that mapping within contentful - for example in a CT which you use for that exact purpose.

I am not familiar with metalsmith but I guess you could access the `sys` object similar to how you access `fields`
```
sys.contentType.sys.id
```
This is where you access the contentType of an entry.

**Comment by dohomi** [comment]
Hi @floelhoeffel thanks for your thoughts. That was exactly what I am looking for: what is the best option to map a contentType to a handlebar template. Look at this example: https://github.com/contentful-labs/contentful-metalsmith-example/blob/master/layouts/entries.html It shows how the entries are grouped, but I would love to see an example where the contentType is ordered by the content object array and rendered through some sort of handlebar helper. Thanks for the hint with `sys.contentType.sys.id`

**Comment by Khaledgarbaya** [comment]
maybe @stefanjudis can answer that ?

**Comment by dohomi** [comment]
I went one step further:
```
    {{#each data.entries}}
    {{#each fields.content as |content|}}
    {{#with sys.contentType.sys}}
    {{> (lookup . "id") content}}
    {{/with}}
    {{/each}}
    {{/each}}
```
With dynamic handlebar helpers I'm one step further and could render the first nodes of my content. But as one of my contentTypes has a nested `GETTER` array I'm looking for an option to render the nested content.  
```
{ title: 'Some headline for testimonial array', testimonialList: [Getter] }
```

**Comment by stefanjudis** [comment]
I'd approach this with another helper.

E.g. I just prototyped breadcrumbs for nested data structure. The helper functions are automatically loaded in my stack here.

```
// breadcrumbs.js

module.exports = function (context, options) {
  function getTreePath(path, entry) {
    path = path || '';

    path = path ?
          entry.fields.slug + ' | ' + path :
          entry.fields.slug;

    if (entry.fields.parent) {
      return getTreePath(path, entry.fields.parent);
    }

    return path;
  }
  
  // return the preferred rendered part
  return getTreePath(null, context);
};
```


```
<!doctype html>
<html lang="en">
<head>
  <!-- ... -->
</head>
<body>
    <!-- ... -->
    {{#breadcrumbs data}}{{/breadcrumbs}}
    <!-- ... -->
```

Does this help?

**Comment by dohomi** [comment]
@stefanjudis the breadcrumb example is not exactly I'm looking for. Is it possible that there is only a certain deepness of nesting available? This is how fields of my page looks like:
```
-- fields
    -- contentType: [Content]
       -- contenType: Hero
       -- contentType: [Testimonials]
           -- contentType: Testimonial
```
`Testimonials` represents an array of  `Testimonial` and is nested inside of array `Content`. It seems I need to fetch this content Type again through the API-client of contentful?

**Comment by stefanjudis** [comment]
> Is it possible that there is only a certain deepness of nesting available?

The maximum deepness we support is 10 levels deep right now. Are you going over this already?

A simple `{{#each}}` should to the trick.

**Comment by dohomi** [comment]
No I'm not 10 levels deep.. for what I understand:
```
PAGE
  -- fields
    -- content
      -- fields
        -- testimonialList
```
Inside of my page.html:
```
 {{#each data.entries}}
    {{#each fields.content as |content|}}
    {{#with sys.contentType.sys}}
    {{> (lookup . "id") content}}
    {{/with}}
    {{/each}}
{{/each}}
```
Inside of my testimonialList.html:
```
{{#with fields}}
<h3>{{title}}</h3>
{{#each testimonialList}}
<h2>this getting called 2 times.. but without fields</h2>
{{log this}}
{{/each}}
{{/with}}
```
output:
```
{ sys: { type: 'Link', linkType: 'Entry', id: '4PbYSvRRBCKscc86K6Keeu' } }
{ sys: { type: 'Link', linkType: 'Entry', id: '6B9nCBx8fCqK4EiGoaYqGI' } }
```

`#each`didn't solve the problem, all why is inside of my elements is the above output.

**Comment by stefanjudis** [comment]
hmm... according to our API docs we default to `1`

> The maximum number of inclusions is 10. The default number, if the parameter is not specified, is 1. If you want no inclusions at all, you should set it to 0.

I don't run into this issues. I'll investigate further tomorrow.

**Comment by dohomi** [comment]
Hi @stefanjudis, thanks pointing me to the docs. I got now the correct number of elements with raising the include filter:
```
---
title: Startpage
contentful:
  content_type: page
  filter:
    query: 'startpage'
    include: 3
layout: index.html
---
```
