### ISSUE TITLE
Best way building a navigation

### ISSUE THREAD

**Issue by dohomi** [contentful-labs/contentful-metalsmith#41]
Is there any recommended way building a navigation based on a parent attribute object reference of a page type?
```
PAGE
  -- parent: PAGE
```
I'd like to render a simple navigation. Any recommended way to do this? I've seen the breadcrumb example, but on the current page there is no reference to the `children`.
Thanks!

**Comment by stefanjudis** [comment]
For navigation purposes maybe https://github.com/contentful-labs/contentful-metalsmith/blob/master/docs/global-settings.md#common-optional helps.

You could fetch whatever you need for the navigation and use it then in your templates.

Does this help?

**Comment by dohomi** [comment]
Yes thanks, that is making sense. I'd need to 
```
"common": {
    "navigationPages": {
      "content_type": "page"
      "filter":{
         "excludeNavigation[exists]": false
      }
    }
  }
```
Is there a good filter to exclude a page with a checkbox like `excludeNavigation`? I was searching for `not-exists`..

**Comment by stefanjudis** [comment]
You can find all this information on the content delivery API documentation.

https://www.contentful.com/developers/docs/references/content-delivery-api/

> Is there a good filter to exclude a page with a checkbox like excludeFromNavigation?

Have you checked the **equality operator**? 

https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/equality-operator/query-entries?console=1

Using it you can filter for booleans easily.

👉  `https://cdn.contentful.com/spaces/YOUR_SPACE/entries?access_token=YOUR_TOKEN&content_type=brand&fields.bool=true`

> Does the API being able to limit the fetched entries from each page?

You can choose what  you want to get using the **selected operator**.

https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/select-operator/query-entries?console=1

Hopes that helps?

**Comment by dohomi** [comment]
@stefanjudis Thanks for your links, worked out very well.
