### ISSUE TITLE
Undefined is not a function

### ISSUE THREAD

**Issue by surajdalvi** [contentful-labs/contentful-metalsmith#5]
I am getting this error in "metalsmith-templates/lib/index.js" line number 42.
var tmpl = metalsmith.join(dir, data.template);

metalsmith.join this method is not part of metalsmith object we receive.

Please could you help me.

**Comment by madtrick** [comment]
@surajdalvi could you paste the stacktrace you get when hitting this issue?

**Comment by surajdalvi** [comment]
Hi,
 
   I get above error in  "metalsmith-templates/lib/index.js" . I get following response:

      Metalsmith · undefined is not a function

TypeError: undefined is not a function
    at convert (D:\Node Example\A\node_modules\metalsmith-templates\lib\index.js
:42:29)
    at D:\Node Example\A\node_modules\metalsmith-templates\node_modules\async\li
b\async.js:111:13
    at Array.forEach (native)
    at _each (D:\Node Example\A\node_modules\metalsmith-templates\node_modules\a
sync\lib\async.js:32:24)
    at async.each (D:\Node Example\A\node_modules\metalsmith-templates\node_modu
les\async\lib\async.js:110:9)
    at Ware.<anonymous> (D:\Node Example\A\node_modules\metalsmith-templates\lib
\index.js:33:5)
    at Ware.<anonymous> (C:\Users\SurajD\AppData\Roaming\npm\node_modules\metals
mith\node_modules\ware\node_modules\wrap-fn\index.js:45:19)
    at next (C:\Users\SurajD\AppData\Roaming\npm\node_modules\metalsmith\node_mo
dules\ware\lib\index.js:75:20)
    at C:\Users\SurajD\AppData\Roaming\npm\node_modules\metalsmith\node_modules\
ware\node_modules\wrap-fn\index.js:121:18
    at done (D:\Node Example\A\node_modules\contentful-metalsmith\node_modules\a
sync\lib\async.js:135:19)




Please help me into these?

**Comment by surajdalvi** [comment]
Hi

 **metalsmith-templates** file consiste following code:


var consolidate = require('consolidate');
var debug = require('debug')('metalsmith-templates');
var each = require('async').each;
var extend = require('extend');

/**
 * Expose `plugin`.
 */

module.exports = plugin;

/**
 * Metalsmith plugin to run files through any template in a template `dir`.
 *
 * @param {String or Object} options
 *   @property {String} engine
 *   @property {String} directory (optional)
 * @return {Function}
 */

function plugin(opts){
  if ('string' == typeof opts) opts = { engine: opts };
  opts = opts || {};
  var engine = opts.engine;
  var dir = opts.directory || 'templates';

  if (!opts.engine) throw new Error('"engine" option required');

  return function(files, metalsmith, done){
    var metadata = metalsmith.metadata();

    each(Object.keys(files), convert, done);

    function convert(file, done){
      debug('checking file: %s', file);
      var data = files[file];
      if (!data.template) return done();

      debug('converting file: %s', file);
      data.contents = data.contents.toString();
	  //var tmpl = require("path").join(dir, data.template);
      var tmpl = metalsmith.join(dir, data.template);
      var clone = extend({}, metadata, data);

      consolidate[engine](tmpl, clone, function(err, str){
        if (err) return done(err);
        data.contents = new Buffer(str);
        debug('converted file: %s', file);
        done();
      });
    }
  };
}





When i write 
**var tmpl = require("path").join(dir, data.template);
   // var tmpl = metalsmith.join(dir, data.template);**

It work fine But when it consists  only 
**var tmpl = metalsmith.join(dir, data.template);**

these it give me  above  error

Please Help me?

**Comment by surajdalvi** [comment]
Hi,

Please Help me on  above question?

**Comment by madtrick** [comment]
@surajdalvi this seems to be an issue in the `metalsmith-templates` library and not with our plugin. I think it would be better if you open an issue on their repo.
