### ISSUE TITLE
Interoperation with metalsmith-permalinks?

### ISSUE THREAD

**Issue by gfscott** [contentful-labs/contentful-metalsmith#9]
First off, thanks for this Metalsmith plugin, really appreciate it. But I've been stumped trying to figure out how to get it to play nice with metalsmith-permalinks.

For, say, a series of Contentful entries about sandwiches I can easily produce permalinks like `site.com/9s0YpYfmzKAq4S68SIa4yC/`, but I can’t figure out how to get it to produce, for instance, `site.com/sandwich/croque-monsieur/`. The Contentful entry has a required field called `sandwichName`, but I can't figure out how to access that value with the permalinks plugin; only the ID.

In my `metalsmith.json file, I'm setting the permalink like this:
```javascript
"metalsmith-permalinks": {
    "pattern": ":id"
}
```
...and that works, producing the first sort of permalink. But (after lots of trying, I promise) I don't know what pattern would construct more semantically meaningful URLs.

I suspect this is doable and I'm just being dumb. Any help appreciated.

**Comment by wconnorwalsh** [comment]
@gfscott any luck with this? Having the same issue.

**Comment by gfscott** [comment]
@wconnorwalsh Afraid not, but haven't taken another crack at it yet. Any thoughts, @madtrick?

**Comment by woodyrew** [comment]
@wconnorwalsh @gfscott, I've done a pull request that might help with this - #10  It allows you to configure the path and filenames it will create.  The [config documentation](https://github.com/woodyrew/metalsmith-contentful#entry-filename-config) is viewable on the fork I created.

**Comment by grncdr** [comment]
Closed by #10, new release coming soon!
